# ### Get all chat rooms
# GET http://localhost:4000/chatrooms
# Accept: application/json

# ###

# ### Get single chat room by ID
# GET http://localhost:4000/chatrooms/{{roomId}}
# Accept: application/json

# ###

# ### Create a chat room
# POST http://localhost:4000/chatrooms
# Content-Type: application/json

# {
#   "name": "My First Room"
# }

# ###

# ### Update chat room name
# PUT http://localhost:4000/chatrooms/{{roomId}}
# Content-Type: application/json

# {
#   "name": "Updated Room Name"
# }

# ###

# ### Delete a chat room
# DELETE http://localhost:4000/chatrooms/{{roomId}}
# Accept: application/json
